//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BAH.MusicPerformanceTracker.PL
{
    using System;
    using System.Collections.Generic;
    
    public partial class SearchLog
    {
        public System.Guid SearchId { get; set; }
        public Nullable<System.DateTime> SearchDate { get; set; }
        public string SearchLevel { get; set; }
        public string SearchLogger { get; set; }
        public string SearchQuery { get; set; }
        public string SearchTable { get; set; }
    }
}
