//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BAH.MusicPerformanceTracker.PL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblComposer
    {
        public System.Guid Id { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public Nullable<System.Guid> GenderId { get; set; }
        public Nullable<System.Guid> RaceId { get; set; }
        public Nullable<System.Guid> LocationId { get; set; }
        public string Bio { get; set; }
    }
}
