//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BAH.MusicPerformanceTracker.PL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblPerformance
    {
        public System.Guid Id { get; set; }
        public System.DateTime PerformanceDate { get; set; }
        public string Location { get; set; }
        public string Name { get; set; }
        public string pdfPath { get; set; }
        public string Description { get; set; }
    }
}
