//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BAH.MusicPerformanceTracker.PL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblPerformancePiece
    {
        public System.Guid Id { get; set; }
        public Nullable<System.Guid> DirectorId { get; set; }
        public System.Guid GroupId { get; set; }
        public System.Guid PerformanceId { get; set; }
        public System.Guid PieceId { get; set; }
        public string Notes { get; set; }
        public string MP3Path { get; set; }
    }
}
