BEGIN
	INSERT INTO [music].tblDirector(Id, FirstName, LastName, BirthDate, Bio)
	VALUES
	(NEWID(), 'Philip', 'Klickman', '1985-10-05', 'Professor Philip Klickman joined the St. Norbert College music faculty in the fall of 2017. His duties include conducting the Wind Ensemble and the Concert Band, and teaching courses in conducting and instrumental music education. Professor Klickman also serves as director of the St. Norbert Community Band. Professor Klickman previously served as the director of bands at Frostburg State University in Frostburg, Maryland, where he conducted the Wind Ensemble and the Marching Bobcats, and taught courses in conducting and instrumental music education. He was also the Collegiate Membership Chair for the Maryland Music Educators Association. Prior to his collegiate career, Professor Klickman taught public school music in the suburbs of Chicago, Illinois. He is a member of the College Band Directors National Association, the College Music Society, the National Association for Music Education, the Society for Music Teacher Education and the International Horn Society.'),
	(NEWID(), 'Eric', 'High', '1985-09-06', 'Eric High has been associate professor of music at St. Norbert College since 2005. Prior to his appointment at St. Norbert, Eric taught public school in Gilbert, Ariz., for five years. An active performer, Eric has given recitals in Minnesota, Arizona, Tennessee and Wisconsin. While living in Arizona, he played with the Arizona Opera, the Salt River Brass Band and the Southwest Brass, and he was the bass trombonist with the Bear Valley Music Festival Orchestra in Bear Valley, Calif. Since moving to Wisconsin, Eric has performed with the Green Bay Symphony Orchestra, the Fox Valley Symphony and the Brass Circle Quintet. He has been featured as a soloist with the SNC Community Band, the N.E.W. Concert Band and the Lakeshore Wind Ensemble.
At SNC, Eric teaches Low Brass, Brass Ensembles, Jazz Ensemble, Evolution of Jazz, and Music Appreciation. Eric’s doctoral research document, “The Contrabass Trombone: A Brief History and Survey Regarding its Use Today,” has led to his continued research about the instrument. In addition, he has had numerous audio and literature reviews published in the International Trombone Association Journal.'),
	(NEWID(), 'Broderick', 'Lemke', '1996-05-03', 'Broderick Lemke is a native of the Fox Valley region of North East Wisconsin. He has a Bachelor''s degree in Music Liberal Arts, and is finishing his last semester of an Associate''s degree in Software Development. Using the combination of knowledge amassed through his education, he hopes to bring creativity, logic and unique outlook to anything he does in his life. In his free time, he works on software and web development projects, composes music, creates art and plays dungeons and dragons with his friends. He has had musical works performed by several local ensembles and continues to create new works in both the visual and musical arts to keep his mind fresh. He is looking forward to harnessing his creativity in new ways over the next few years and creating digital content that explores relationships between technology and the arts.')

END
GO