CREATE TABLE [music].[tblComposer]
(
	[Id] UNIQUEIDENTIFIER NOT NULL PRIMARY KEY, 
    [FirstName] VARCHAR(50) NOT NULL, 
    [LastName] VARCHAR(50) NOT NULL, 
    [GenderId] UNIQUEIDENTIFIER NULL, 
    [RaceId] UNIQUEIDENTIFIER NULL, 
    [LocationId] UNIQUEIDENTIFIER NULL, 
    [Bio] TEXT NULL
)
