CREATE TABLE [music].[tblComposer]
(
	[Id] UNIQUEIDENTIFIER NOT NULL PRIMARY KEY, 
    [FirstName] VARCHAR(50) NOT NULL, 
    [LastName] VARCHAR(50) NOT NULL, 
    [Gender] UNIQUEIDENTIFIER NULL, 
    [Race] UNIQUEIDENTIFIER NULL, 
    [Location] UNIQUEIDENTIFIER NULL, 
    [Bio] TEXT NULL
)
