CREATE TABLE [music].[tblGroupMember]
(
	[Id] UNIQUEIDENTIFIER NOT NULL PRIMARY KEY, 
    [GroupId] UNIQUEIDENTIFIER NOT NULL, 
    [PerformerId] UNIQUEIDENTIFIER NOT NULL, 
    [StartDate] DATETIME NOT NULL, 
    [EndDate] DATETIME NULL, 
    [Instrument] UNIQUEIDENTIFIER NOT NULL
)
