CREATE TABLE [music].[tblPieceWriter]
(
	[Id] UNIQUEIDENTIFIER NOT NULL PRIMARY KEY, 
    [PieceId] UNIQUEIDENTIFIER NOT NULL, 
    [ComposerId] UNIQUEIDENTIFIER NOT NULL, 
    [ComposerTypeId] UNIQUEIDENTIFIER NOT NULL
)
