CREATE TABLE [music].[tblPerformancePiece]
(
	[Id] UNIQUEIDENTIFIER NOT NULL PRIMARY KEY, 
    [DirectorId] UNIQUEIDENTIFIER NULL, 
    [GroupId] UNIQUEIDENTIFIER NOT NULL, 
    [PerformanceId] UNIQUEIDENTIFIER NOT NULL, 
    [PieceId] UNIQUEIDENTIFIER NOT NULL, 
    [Notes] VARCHAR(255) NULL, 
    [MP3Path] VARCHAR(255) NULL
)
